spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_service
    username: postgres
    password: biba
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql